# üêº Pandas Practice: DataFrames, Selection, Mapping, and More

In [2]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah']
departments = ['Sales', 'Marketing', 'HR', 'Tech']

# Create a DataFrame
df = pd.DataFrame({
    'Name': np.random.choice(names, size=20),
    'Age': np.random.randint(22, 60, size=20),
    'Department': np.random.choice(departments, size=20),
    'Salary': np.random.randint(40000, 120000, size=20),
    'YearsExperience': np.random.randint(0, 20, size=20)
})
df.head()

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

# üß™ PRACTICE QUESTIONS BELOW


# 1Ô∏è‚É£ Use .loc to select all rows where the Department is 'Tech'.
#    - Describe what .loc does and why it's useful for label-based filtering.

In [3]:
tech_df = df.loc[df['Department'] == 'Tech']
print(tech_df)

       Name  Age Department  Salary  YearsExperience
2     Ethan   45       Tech  109479               17
4   Charlie   59       Tech  106557               12
12  Charlie   49       Tech  111211               11
13  Charlie   37       Tech  105697                7
15    Ethan   24       Tech   72606               18
17   Hannah   28       Tech   80397                7
19  Charlie   30       Tech   95591                2


# 2Ô∏è‚É£ Use .iloc to select the first 5 rows and the last two columns.
#    - What is the difference between .loc and .iloc?

In [4]:
df.iloc[:5, -2:]

   Salary  YearsExperience
0   75920               15
1  107121               12
2  109479               17
3   59457               14
4  106557               12


# 3Ô∏è‚É£ Map a new column called 'DeptCode' where:
#     'Sales' -> 1, 'Marketing' -> 2, 'HR' -> 3, 'Tech' -> 4.
#    - Use .map and explain what happens if a value is not mapped.

In [5]:
dept_map = {'Sales': 1, 'Marketing': 2, 'HR': 3, 'Tech': 4}
df['DeptCode'] = df['Department'].map(dept_map)
df

       Name  Age Department  Salary  YearsExperience  DeptCode
0    George   43         HR   75920               15         3
1     Diana   23  Marketing  107121               12         2
2     Ethan   45       Tech  109479               17         4
3    George   51      Sales   59457               14         1
4   Charlie   59       Tech  106557               12         4
5    Hannah   23  Marketing  117189                8         2
6     Ethan   42  Marketing  118953               14         2
7     Ethan   54  Marketing   92995               12         2
8    George   33      Sales   80757                0         1
9       Bob   43  Marketing   49692                6         2
10  Charlie   46      Sales   85758                8         1
11   George   48  Marketing  112409                0         2
12  Charlie   49       Tech  111211               11         4
13  Charlie   37       Tech  105697                7         4
14   Hannah   36         HR   77065               10         3
15    Ethan   24       Tech   72606               18         4
16    Diana   58         HR   51534               16         3
17   Hannah   28       Tech   80397                7         4
18   Hannah   42      Sales   41016                2         1
19  Charlie   30       Tech   95591                2         4


# 4Ô∏è‚É£ Use .apply to calculate a new column 'Seniority' where:
#     - If YearsExperience > 10 ‚Üí 'Senior'
#     - If between 5-10 ‚Üí 'Mid-Level'
#     - Else ‚Üí 'Junior'
#    - Use a lambda function with apply.

In [6]:
df['Seniority'] = df['YearsExperience'].apply(
    lambda x: 'Senior' if x > 10 else 'Mid-Level' if x >= 5 else 'Junior'
)
df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   80757                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing  112409                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   41016                2         1     Junior
19  Charlie   30       Tech   95591                2         4     Junior


# 5Ô∏è‚É£ Overwrite all salaries for employees with < 3 years of experience to 35000.
#    - Use boolean indexing with .loc to do this.

In [7]:
df.loc[df['YearsExperience'] < 3, 'Salary'] = 35000
df

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 6Ô∏è‚É£ Compare using .loc and .iloc to select the same row:
#    - Select the 3rd row using .iloc
#    - Find its index value and use .loc to select the same row by label

In [8]:
row_iloc = df.iloc[2]
index_label = df.index[2]
row_loc = df.loc[index_label]
row_iloc.equals(row_loc)

True


# 7Ô∏è‚É£ Check if there are any duplicate names in the dataset.
#    - If there are, show only those duplicated rows.

In [9]:
duplicates = df[df.duplicated(subset='Name', keep=False)]
duplicates

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 8Ô∏è‚É£ Sort the DataFrame by Salary in descending order.
#    - Then sort it by Department and within Department by Age.

In [10]:
df_sorted_salary = df.sort_values(by='Salary', ascending=False)
df_sorted_dept_age = df.sort_values(by=['Department', 'Age'])


# 9Ô∏è‚É£ Slice the DataFrame to return rows 5 through 12 and columns 'Name', 'Salary'
#    - Try slicing using both label-based and position-based methods.

In [11]:
# Label-based
df.loc[5:7, ['Name', 'Salary']]

# Position-based
df.iloc[5:8, [0, 4]]

     Name  YearsExperience
5  Hannah                8
6   Ethan               14
7   Ethan               12


# üîü Find all rows where the name starts with 'A' or 'D'.
#    - Use string methods with .str accessor.

In [12]:
df[df['Name'].str.startswith(('A', 'D'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior


# 1Ô∏è‚É£1Ô∏è‚É£ Drop all rows where Age is below 25.
#     - Explain whether this modifies the DataFrame in place or returns a copy.

In [13]:
df_filtered = df[df['Age'] >= 25]

df.drop(df[df['Age'] < 25].index, inplace=True)


# 1Ô∏è‚É£2Ô∏è‚É£ Use groupby to calculate the average salary per Department.
#     - Bonus: Show the average age and average experience too.

In [14]:
df.groupby('Department')[['Salary', 'Age', 'YearsExperience']].mean()

                  Salary        Age  YearsExperience
Department
HR          68173.000000  45.666667        13.666667
Marketing   74160.000000  46.750000         8.000000
Sales       53803.750000  43.000000         6.000000
Tech        91390.166667  41.333333         9.333333


# 1Ô∏è‚É£3Ô∏è‚É£ Use groupby to count how many employees are in each Department.

In [15]:
df['Department'].value_counts()

df.groupby('Department').size()

Department
HR           3
Marketing    4
Sales        4
Tech         6
dtype: int64


# 1Ô∏è‚É£4Ô∏è‚É£ Use .apply to normalize the Salary column (min-max scaling between 0 and 1).
#     - Bonus: Write your own normalization function and pass it to apply.

In [18]:
def normalize(series):
    return (series - series.min()) / (series.max() - series.min())

df['NormalizedSalary'] = normalize(df['Salary'])


# 1Ô∏è‚É£5Ô∏è‚É£ Use boolean indexing to find all employees who:
#     - Are in 'HR' OR 'Tech', AND have > 5 years of experience.

# üîÅ For many of these tasks, try both .loc and .iloc to build intuition on their differences.

In [17]:
df[(df['Department'].isin(['HR', 'Tech'])) & (df['YearsExperience'] > 5)]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
4   Charlie   59       Tech  106557               12         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level